# Generated by Django 3.1.5 on 2021-07-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Profileimage',
            field=models.ImageField(blank=True, default="<img src='https://img.icons8.com/ios/50/000000/user--v1.png'/>", null=True, upload_to='userimage'),
        ),
    ]
