# Generated by Django 3.1.5 on 2021-08-01 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20210731_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='postartical',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
