# Generated by Django 3.1.5 on 2021-08-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_postartical_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postartical',
            options={'ordering': ['-date']},
        ),
    ]
