# Generated by Django 3.1.5 on 2021-08-04 06:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20210801_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='postartical',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
