# Generated by Django 3.1.5 on 2021-08-04 06:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_postartical_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postartical',
            name='content',
        ),
        migrations.AlterField(
            model_name='postartical',
            name='Artical',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
