# Generated by Django 3.1.5 on 2021-08-04 06:55

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20210804_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='postartical',
            name='content',
            field=djrichtextfield.models.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
