# Generated by Django 3.1.5 on 2021-08-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_postartical_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postartical',
            name='content',
        ),
    ]
